apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  type: NodePort  # Expose via node port
  selector:
    app: capstone
  ports:
  - protocol: TCP
    port: 8082         # Service port inside cluster
    targetPort: 8082   # Container port
    nodePort: 30080    # Port on node (localhost:30080)
